package com.cyl.spring.database.jdbc.example;

import org.junit.*;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

public class TestBestPractice {
    private static JdbcTemplate jdbcTemplate;

    @BeforeClass
    public static void setUpClass() {
        String url = "jdbc:hsqldb:mem:test";
        String userName = "sa";
        String passWord = "";
        DriverManagerDataSource dataSource = new DriverManagerDataSource(url, userName, passWord);
        dataSource.setDriverClassName("org.hsqldb.jdbcDriver");
        jdbcTemplate = new JdbcTemplate(dataSource);
    }

    @Before
    public void setUp() {
        String creatTableSql = "CREATE MEMORY TABLE test " +
                "(id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name VARCHAR(100))";
        jdbcTemplate.update(creatTableSql);
    }

    @After
    public void tearDown() {
        String dropTableSql = "DROP TABLE test";
        jdbcTemplate.update(dropTableSql);
    }
    @Test
    public void test() {
        String[] configLocations = new String[]{"spring/jdbc/example/application-resources.xml","spring/jdbc/example/jdbc.xml"};
        ApplicationContext applicationContext = new ClassPathXmlApplicationContext(configLocations);
        IUserDao userDao = applicationContext.getBean(IUserDao.class);
        UserModel model = new UserModel();
        model.setMyName("test");
        userDao.save(model);
        Assert.assertEquals(1,userDao.countAll());
    }
}
